-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgCTo5/RJ4QfaJeNO6
k51G9TrxplidrOkUHLC/ojhGxWigCgYIKoZIzj0DAQehRANCAAS5VpXm3Qqj9Xcb
fkqPXG4z4kroGSyRNVtPM199Kre3K/QwFqPG/G6hjJ7imhO9t2MwfZ4txxHOzKxY
NqMCrmZB
-----END PRIVATE KEY-----