name: bausch
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.2.0+95

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  after_layout: ^1.2.0
  app_links: ^3.3.0
  appsflyer_sdk: ^6.8.2
  auto_size_text: ^3.0.0
  auto_size_text_pk: ^3.0.0
  bottom_sheet: ^3.1.2
  cookie_jar: ^3.0.1
  csv: ^5.0.1
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  dio_cache_interceptor: ^3.3.1
  dio_cache_interceptor_db_store: ^5.0.0
  dio_cookie_manager: ^2.0.0
  dotted_line: ^3.1.0
  easy_mask: ^2.0.1
  email_validator: ^2.1.17
  equatable: ^2.0.5
  extended_image: ^6.3.2
  extended_masked_text: ^2.3.1
  file_picker: ^5.2.2
  firebase_analytics: ^10.0.5
  firebase_core: ^2.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_cache_manager: ^3.3.0
  flutter_compass: ^0.7.0
  flutter_html: ^2.2.1
  flutter_keyboard_visibility: ^5.3.0

  flutter_localizations:
    sdk: flutter
  flutter_native_timezone: ^2.0.0
  flutter_svg: ^0.23.0 # НЕ ОБНОВЛЯТЬ
  fwfh_text_style: ^2.22.8+1
  geolocator: ^9.0.2
  http: ^0.13.5
  image: ^3.1.3 # Для иконки на карте
  intl: ^0.17.0
  iphone_has_notch: ^1.0.0
  menu_button: ^1.4.2+1

  mindbox: ^1.0.2 # НЕ ОБНОВЛЯТь
  overlay_support: ^2.0.1
  package_info: ^2.0.2
  path_provider: ^2.0.11
  pdf_viewer_plugin: ^2.0.1

  percent_indicator: ^4.2.2
  pin_code_fields: ^7.4.0
  platform_device_id: ^1.0.1
  provider: ^6.0.4
  pull_to_refresh_notification: ^2.3.0
  responsive_framework: ^0.2.0
  share: ^2.0.4
  shared_preferences: ^2.0.15
  sqlite3_flutter_libs: ^0.5.9 # НЕ УДАЛЯТЬ
  surf_mwwm: ^2.0.2
  url_launcher: ^6.1.6
  vimeoplayer_trinity:
    path: lib/packages/vimeoplayer_trinity
  visibility_detector: ^0.2.0 # НЕ ОБНОВЛЯТЬ
  webview_flutter: ^2.0.4
  yandex_mapkit: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  surf_lint_rules: ^1.5.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logos/
    - assets/icons/
    - assets/loading/

  fonts:
    - family: Euclid Circular A
      fonts:
        - asset: fonts/EuclidCircularA-Regular.ttf
        - asset: fonts/EuclidCircularA-Italic.ttf
          style: italic
        - asset: fonts/EuclidCircularA-Medium.ttf
          weight: 500
        - asset: fonts/EuclidCircularA-MediumItalic.ttf
          weight: 500
          style: italic
